function getMonth() {
    var curdate = new Date();
    var month = curdate.getMonth() + 1;
    return month;
}

function getDay() {
    var curdate = new Date();
    var day = curdate.getDate() + 1;
    return day;
}

function checkDate(dateNeeded) {
    var currentMonth = getMonth();
    var currentDay = getDay();
    var responseStr = " ";
    if (currentMonth == 12) {
        if (currentDay > dateNeeded) {
            responseStr = stringInfo(dateNeeded);
        }
        else {
            responseStr = "You can't skip ahead to this date. Sorry!<br /> To go back, click the 3 dots in the bottom<br /> right corner and then press back.";
        }
    }
    else {
        responseStr = "Hey, it's not even December yet! You'll have to wait a bit longer. <br />To go back, click the 3 dots in the bottom<br /> right corner and then press back.";
    }

    document.getElementById("response").innerHTML = responseStr;
}

function stringInfo(dayToDisplay)
{
	switch (dayToDisplay)
	{
		case 1:
		  retString = "<h1>Advent Calendar <br />Craft Guides:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Craft Crow</b><br> <a href=\"http://www.thecraftycrow.net/2012/11/35-great-homemade-advent-calendar-ideas.html\" target=_blank><img src=\"http://belladia.typepad.com/.a/6a00d8341cc08553ef017d3e1125e5970c-800wi\" alt=\"Crafty Crow\" width=\"275\" height=\"336\"></a> <br><br> <b>AllCrafts</b><br> <a href=\"http://www.allcrafts.net/xmas/advent-calendars.htm\" target=_blank><img src=\"http://www.marthastewart.com/sites/files/marthastewart.com/images/content/pub/kids/2001Q4/ka98981_hol01_advent_xl.jpg\" alt=\"AllCrafts\" width=\"275\" height=\"344\"></a> <br><br> <b>All About You</b><br> <a href=\"http://www.allaboutyou.com/craft/Christmas-craft-ideas-advent-calendars\" target=_blank><img src=\"http://www.allaboutyou.com/cm/allaboutyou/images/sf/HB-blackboard-advent-calendar-s8LgHW-300x400.jpg\" alt=\"All About You\" width=\"275\" height=\"367\"></a> <br><br> <b>Apartment Therapy</b><br> <a href=\"http://www.apartmenttherapy.com/countdown-to-christmas-35-diy-advent-calendars-to-make-roundup-197137\" target=_blank><img src=\"http://p-ec1.pixstatic.com/52823800697ab00e10005c98._w.540_s.fit_.jpg\" alt=\"Apartment Therapy\" width=\"275\" height=\"376\"></a> <br><br> <b>BlogHer</b><br> <a href=\"http://www.blogher.com/10-advent-calendar-crafts-you-can-make?page=full\" target=_blank><img src=\"https://www.blogher.com/files/outdoor-advent.jpg\" alt=\"BlogHer\" width=\"275\" height=\"170\"></a>";
		  break;
		case 2:
		  retString = "<h1>Ginger Bread <br />House Guides:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Food Network</b><br> <a href=\"http://www.foodnetwork.com/recipes/gingerbread-house-recipe/index.html\" target=_blank><img src=\"http://img.foodnetwork.com/FOOD/2012/10/16/FN_Gingerbread-House-Process-05-Recipe-Shot_s4x3_lg.jpg\" alt=\"Food Network\" width=\"275\" height=\"206\"></a> <br><br> <b>Simply Recipes</b><br> <a href=\"http://www.simplyrecipes.com/recipes/how_to_make_a_gingerbread_house/\" target=_blank><img src=\"http://www.simplyrecipes.com/photos/gingerbread-house-2.jpg\" alt=\"Simply Recipes\" width=\"275\" height=\"183\"></a> <br><br> <b>King Arthur Flour</b><br> <a href=\"http://www.kingarthurflour.com/baking/documents/gingerbread.pdf\" target=_blank><img src=\"http://search.kingarthurflour.com/thumb.php?s=220&f=http://www.kingarthurflour.com/item-img/3921_09_04_2013__15_32_31_214\" alt=\"King Arthur Flour\" width=\"275\" height=\"275\"></a>";
		  break;
		case 3:
		  retString = "<h1>Ornament Origami:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Origami Club</b><br> <a href=\"http://en.origami-club.com/xmas/\" target=_blank><img src=\"http://en.origami-club.com/flowers/poinsettia/poinsettia.jpg\" alt=\"Origami Club\" width=\"275\" height=\"247\"></a> <br><br> <b>Origami-Fun</b><br> <a href=\"http://www.origami-fun.com/christmas-origami.html\" target=_blank><img src=\"http://www.origami-fun.com/images/xmas-trees.gif\" alt=\"Origami-Fun\" width=\"275\" height=\"275\"></a> <br><br> <b>Origami Resource Center</b><br> <a href=\"http://www.origami-resource-center.com/christmas-ornaments.html\" target=_blank><img src=\"http://www.origami-resource-center.com/images/christmasOrnament3in1RabbitEar.jpg\" alt=\"Origami Resource Center\" width=\"275\" height=\"275\"></a> <br><br> <b>HGTV</b><br> <a href=\"http://www.hgtv.com/handmade/make-an-origami-christmas-ornament/index.html\" target=_blank><img src=\"http://hgtv.sndimg.com/HGTV/2012/11/18/Original_Manvi-Hidalgo-butterfly-ornaments-beauty_s3x4_lg.jpg\" alt=\"HGTV\" width=\"275\" height=\"367\"></a> <br><br> <b>How About Orange</b><br> <a href=\"http://howaboutorange.blogspot.com/2007/12/paper-3-d-holiday-ornament-tutorials.html\" target=_blank><img src=\"http://2.bp.blogspot.com/_wXG-O0Gal_o/R2FV77SnA2I/AAAAAAAABG8/oiaaFa-l0Gc/s400/3D-paper-snowflakes.jpg\" alt=\"How About Orange\" width=\"275\" height=\"151\"></a>";
		  break;
		case 4:
		  retString = "<h1>Create a <br />Wreath:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>All About You</b><br> <a href=\"http://www.allaboutyou.com/craft/Christmas-crafts-Christmas-wreaths\" target=_blank><img src=\"http://www.allaboutyou.com/cm/allaboutyou/images/ac/md_99f0fe3812593255991513.jpg\" alt=\"All About You\" width=\"275\" height=\"330\"></a> <br><br> <b>The 36th Avenue</b><br> <a href=\"http://www.the36thavenue.com/2011/11/sunday-best-25-christmas-wreath.html\" target=_blank><img src=\"http://www.the36thavenue.com/wp-content/uploads/2011/11/Christmas-Wreath-4.jpg\" alt=\"Origami Club\" width=\"275\" height=\"305\"></a> <br><br> <b>Spoonful</b><br> <a href=\"http://spoonful.com/crafts/recycled-wreathl\" target=_blank><img src=\"http://static.spoonful.com/sites/default/files/styles/square_420x420/public/crafts/recycled-wreath-holiday-craft-photo-420-FF1108BABYA05.jpg?itok=redMiFSm\" alt=\"Spoonful\" width=\"275\" height=\"275\"></a> <br><br> <b>By Stephanie Lynn</b><br> <a href=\"http://www.bystephanielynn.com/2011/11/70-unique-and-unusual-christmas-holiday-wreaths-saturday-inspiration-ideas.html\" target=_blank><img src=\"http://i693.photobucket.com/albums/vv298/theliebertfamily/blog3/a45086c4.jpg\" alt=\"By Stephanie Lynn\" width=\"275\" height=\"206\"></a> <br><br> <b>Save On Crafts</b><br> <a href=\"http://www.save-on-crafts.com/wreatmakandd.html\" target=_blank><img src=\"http://bevfabriccrafts.us-dc1-edit.store.yahoo.net/I/bevfabriccrafts_2087_9769871\" alt=\"Save On Crafts\" width=\"275\" height=\"317\"></a>";
		  break;
		case 5:
		  retString = "<h1>Handmade <br />Gift Tags:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>The Crafty Quilter</b><br> <a href=\"http://thecraftyquilter.com/2013/09/christmas-once-a-month-handmade-gift-tags-more/\" target=_blank><img src=\"http://thecraftyquilter.com/wp-content/uploads/2013/09/tags-straight.jpg\" alt=\"The Crafty Quilter\" width=\"275\" height=\"262\"></a> <br><br> <b>Home Depot</b><br> <a href=\"http://ext.homedepot.com/community/blog/christmas-craft-ideas-ceramic-tile-gift-tag/\" target=_blank><img src=\"http://ext.homedepot.com/community/blog/wp-content/wpuploads/DM_Holiday_Tile_Gift_hero.jpg\" alt=\"Home Depot\" width=\"275\" height=\"220\"></a> <br><br> <b>HGTV</b><br> <a href=\"http://www.hgtv.com/handmade/8-handmade-gift-tag-ideas/pictures/index.html\" target=_blank><img src=\"http://img.hgtv.com/HGTV/2010/09/07/RX-DK-AGX19402_fabric-star-tag_s3x4_lg.jpg\" alt=\"HGTV\" width=\"275\" height=\"367\"></a> <br><br> <b>Better Homes and Gardens</b><br> <a href=\"http://www.bhg.com/christmas/cards/easy-handmade-christmas-gift-tags/\" target=_blank><img src=\"http://images.meredith.com/content/dam/bhg/Images/2008/08/101269459.jpg.rendition.largest.jpg\" alt=\"Better Homes and Gardens\" width=\"275\" height=\"367\"></a> <br><br> <b>Buzzfeed</b><br> <a href=\"http://www.buzzfeed.com/peggy/51-seriously-adorable-gift-tag-ideas\" target=_blank><img src=\"http://s3-ec.buzzfed.com/static/enhanced/webdr03/2012/12/12/12/enhanced-buzz-3418-1355333084-11.jpg\" alt=\"Buzzfeed\" width=\"275\" height=\"362\"></a>";
		  break;
		case 6:
		  retString = "<h1>Christmas Lights:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>DIY Network: Buyers' Guide for Outdoor Christmas Lighting</b><br> <a href=\"http://www.diynetwork.com/outdoors/buyers-guide-for-outdoor-christmas-lighting-2/index.html\" target=_blank><img src=\"http://img.diynetwork.com/DIY/2011/09/22/iStock-14448247_colorful-neon-christmas-light-front-yard_s4x3_al.jpg\" alt=\"DIY Network\" width=\"275\" height=\"207\"></a> <br><br> <b>Houston Christmas Lights: How to Hang Christmas Lights</b><br> <a href=\"http://www.lovechristmaslights.com/home/how-to-hang-christmas-lights\" target=_blank><img src=\"http://www.lovechristmaslights.com/images/how_to/small-home.jpg\" alt=\"Houston Christmas Lights\" width=\"275\" height=\"183\"></a> <br><br> <b>iVillage</b><br> <a href=\"http://www.ivillage.com/ways-decorate-home-christmas-lights/7-b-509316\" target=_blank><img src=\"http://www.ivstatic.com/files/et/imagecache/636/files/slides/Sarah_Finks.jpg\" alt=\"iVillage\" width=\"275\" height=\"206\"></a> <br><br> <b>Examiner</b><br> <a href=\"http://www.examiner.com/slideshow/50-bedrooms-decorated-with-christmas-lights#slide=1\" target=_blank><img src=\"http://cdn2-b.examiner.com/sites/default/files/styles/image_content_width/hash/97/d6/Apartment%20Therapy-4.jpg?itok=IXT9EN5Q\" alt=\"Examiner\" width=\"275\" height=\"184\"></a>";
		  break;
		case 7:
		  retString = "<h1>Handmade <br />Eatable Gifts:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Country Living: 29 Homemade Food Gifts</b><br> <a href=\"http://www.countryliving.com/cooking/about-food/homemade-food-gifts#slide-1\" target=_blank><img src=\"http://www.countryliving.com/cm/countryliving/images/rQ/edible-gifts-flavored-salts-1212-mdn.jpg\" alt=\"Country Living\" width=\"275\" height=\"206\"></a> <br><br> <b>Martha Stewart: 20 Homemade Food Gifts</b><br> <a href=\"http://www.marthastewart.com/274972/homemade-food-gifts/@center/307035/santas-workshop\" target=_blank><img src=\"http://www.marthastewart.com/sites/files/marthastewart.com/imagecache/wmax-330/ecl/images/content/pub/ms_living/2012/december/christmas_crackers/crackers-mld109203_vert.jpg\" alt=\"Martha Stewart\" width=\"275\" height=\"334\"></a> <br><br> <b>Food Network: Edible Gifts to Make</b><br> <a href=\"http://www.foodnetwork.com/holidays-and-parties/edible-gifts-to-make-christmas-and-holiday-ideas/pictures/index.html\" target=_blank><img src=\"http://img.foodnetwork.com/FOOD/2010/11/01/FNM_120110-Edible-Gifts-019_s4x3_lg.jpg\" alt=\"Examiner\" width=\"275\" height=\"206\"></a> <br><br> <b>The Kitchn: 40 Homemade Gifts</b><br> <a href=\"http://www.thekitchn.com/homemade-holiday-gifts-from-th-133621\" target=_blank><img src=\"http://p-ec2.pixstatic.com/51bcf321dbd0cb1f11001024._w.540_s.fit_.jpg\" alt=\"The Kitchn\" width=\"275\" height=\"275\"></a> <br><br> <b>Jell-O Delish: Delicious Homemade Food Items</b><br> <a href=\"http://www.delish.com/entertaining-ideas/holidays/christmas/homemade-holiday-food-gifts\" target=_blank><img src=\"http://www.delish.com/cm/delish/images/k5/cookie-ornaments-ENTER1206-lg.jpg\" alt=\"Jell-O Delish\" width=\"275\" height=\"275\"></a> <br><br> <b>Allrecipes: Cranberry Hootycreeks</b><br> <a href=\"http://allrecipes.com/Recipe/Cranberry-Hootycreeks/Detail.aspx?evt19=1\" target=_blank><img src=\"http://images.media-allrecipes.com/userphotos/250x250/00/74/71/747168.jpg\" alt=\"Allrecipes\" width=\"275\" height=\"275\"></a>";
		  break;
		case 8:
		  retString = "<h1>Raffia Crafts:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Mod Podge Rocks: Napkin rings</b><br> <a href=\"http://modpodgerocksblog.com/2012/10/diy-fall-napkin-rings-using-raffia.html\" target=_blank><img src=\"http://modpodgerocksblog.com/wp-content/uploads/2012/10/diy-napkin-rings-raffia-decoupage-fall-072.jpg\" alt=\"Mod Podge Rocks\" width=\"275\" height=\"207\"></a> <br><br> <b>WonderHowTo: Rafia Angel Ornament</b><br> <a href=\"http://holiday-parties.wonderhowto.com/how-to/create-raffia-angel-christmas-ornament-351064/\" target=_blank><img src=\"http://i1.squidoocdn.com/resize/squidoo_images/800/draft_lens21039320module167578706photo_1368227288aa-a_a.jpg\" alt=\"WonderHowTo\" width=\"275\" height=\"275\"></a> <br><br> <b>Happy Hooligans: Raffia Twig Star</b><br> <a href=\"http://happyhooligans.ca/twig-ornaments/\" target=_blank><img src=\"http://happyhooligans.ca/wp-content/uploads/2011/12/img_9615.jpg\" alt=\"Examiner\" width=\"275\" height=\"183\"></a> <br><br> <b>Stone Gable Blog</b><br> <a href=\"http://www.stonegableblog.com/2011/11/raffia-wreath-tutorial.html\" target=_blank><img src=\"http://1.bp.blogspot.com/-KBPziKCXt9s/TqsJGtwNmCI/AAAAAAAAOHs/a4jEKdzNO40/s640/Copy+of+IMG_2173.JPG\" alt=\"The Kitchn\" width=\"275\" height=\"413\"></a> <br><br> <b>YouTube: Gift Wrapping with Rafia</b><br> <a href=\"http://www.youtube.com/watch?v=W7ItXNX11WA\" target=_blank><img src=\"http://lh5.ggpht.com/_Yi0MtghqTE8/SpwUJ2fx31I/AAAAAAAAJ_M/z14m264HLSo/s800/raffia.jpg\" alt=\"YouTube\" width=\"275\" height=\"463\"></a>";
		  break;
		case 9:
		  retString = "<h1>Bow-Making <br />Guide:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Victoria Elizabeth Barnes</b><br> <a href=\"http://victoriaelizabethbarnes.com/step-by-step-guide-to-making-any-size-holiday-bow-diy-ribbon-christmas-decorations/\" target=_blank><img src=\"http://frontgate.scene7.com/is/image/frontgate/62255_BUR_main?$wfih$\" alt=\"Victoria Elizabeth Barnes\" width=\"275\" height=\"275\"></a> <br><br> <b>Koch Blog</b><br> <a href=\"http://www.koch.com.au/blog/diy-ribbon-pom-pom-bow\" target=_blank><img src=\"http://www.koch.com.au/blog/wp-content/uploads/2013/06/KI236.jpg\" alt=\"Koch Blog\" width=\"275\" height=\"381\"></a> <br><br> <b>The Container Store</b><br> <a href=\"http://www.containerstore.com/experthelp/tips/gorgeousGiftPresentation-PomPomBow.html\" target=_blank><img src=\"http://images.containerstore.com/images/experthelp/tips/makingBows/pomPomBowVariation3.jpg\" alt=\"The Container Store\" width=\"275\" height=\"216\"></a> <br><br> <b>Martha Stewart</b><br> <a href=\"http://www.marthastewart.com/264341/ribbon-and-bow-accessory-how-tos\" target=_blank><img src=\"http://www.marthastewart.com/sites/files/marthastewart.com/images/content/pub/ms_living/2004Q4/la_1204_figure8_htd2_xl.jpg\" alt=\"Martha Stewart\" width=\"275\" height=\"342\"></a>";
		  break;
		case 10:
		  retString = "<h1>Soap-Making <br />Guide:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>About.com</b><br> <a href=\"http://candleandsoap.about.com/od/holidayprojects/tp/ChristmasSoapProjects.htm\" target=_blank><img src=\"http://candleandsoap.about.com/gi/o.htm?zi=1/XL&zTi=1&sdn=candleandsoap&cdn=homegarden&tm=53&f=20&su=p284.13.342.ip_p504.6.342.ip_&tt=3&bt=6&bts=6&zu=http%3A//0.tqn.com/d/candleandsoap/1/0/i/m/applecidersoap58.jpg\" alt=\"About.com\" width=\"275\" height=\"206\"></a> <br><br> <b>Martha Stewart</b><br> <a href=\"www.marthastewart.com/275209/bath-and-spa-gifts/@center/307035/santas-workshop\" target=_blank><img src=\"http://www.marthastewart.com/sites/files/marthastewart.com/imagecache/wmax-330/ecl/images/content/pub/special_issues/2006/ml212cc0_hol06_pantrysoap_vert.jpg\" alt=\"Martha Stewart\" width=\"275\" height=\"344\"></a> <br><br> <b>AlphaMom: Snow Globe Soap</b><br> <a href=\"http://alphamom.com/family-fun/holidays/snow-globe-soap/\" target=_blank><img src=\"http://farm4.staticflickr.com/3234/3119927326_dd45da251d.jpg\" alt=\"AlphaMom\" width=\"275\" height=\"413\"></a> <br><br> <b>Organized Christmas: Melt-And-Pour Soap</b><br> <a href=\"http://christmas.organizedhome.com/crafts/melt-and-pour-soap\" target=_blank><img src=\"http://christmas.organizedhome.com/sites/christmas.organizedhome.com/files/styles/medium/public/image/attached/crafts/melt_pour_soap_1.jpg?itok=oNeRVtxf\" alt=\"Organized Christmas\" width=\"275\" height=\"275\"></a> <br><br> <b>Soap Queen</b><br> <a href=\"http://www.soapqueen.com/bramble-berry-news/christmas-mash-up-2/\" target=_blank><img src=\"http://farm4.static.flickr.com/3195/3081137226_642205d91b.jpg\" alt=\"Soap Queen\" width=\"275\" height=\"306\"></a>";
		  break;
		case 11:
		  retString = "<h1>Gift Exchange <br />Tips and Ideas:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Adirondack: 10 Gift Exchange Ideas For Your Holiday Party</b><br> <a href=\"http://www.adirondack.net/holiday/gift-exchange.cfm\" target=_blank><img src=\"http://www.adirondack.net/images/gift-exchange.jpg\" alt=\"Adirondack\" width=\"275\" height=\"165\"></a> <br><br> <b>Yahoo: Top 10 Fun Christmas Gift Exchange Ideas</b><br> <a href=\"http://voices.yahoo.com/top-10-fun-christmas-gift-exchange-ideas-135171.html?cat=24\" target=_blank><img src=\"http://l.yimg.com/ck/image/A3783/37838/300_37838.jpg\" alt=\"Yahoo\" width=\"275\" height=\"269\"></a> <br><br> <b>Escape Adulthood: 7 Fun & Creative Christmas Gift Exchange Ideas</b><br> <a href=\"http://escapeadulthood.com/blog/2010-11-26/7-fun-creative-christmas-gift-exchange-ideas.html\" target=_blank><img src=\"http://kimandjason.com/blog/wp-content/uploads/2010/11/santas_gift.jpg\" alt=\"Escape Adulthood\" width=\"275\" height=\"385\"></a> <br><br> <b>Tatiana: Christmas Gifts for Coworkers: Gift Exchange Ideas</b><br> <a href=\"http://tutta.hubpages.com/hub/christmas-gifts-for-coworkers-and-employees\" target=_blank><img src=\"http://s3.hubimg.com/u/8515586_f248.jpg\" alt=\"Tatiana\" width=\"275\" height=\"272\"></a> <br><br> <b>MomClick: Cheap and fun gift-exchange party ideas</b><br> <a href=\"http://www.heraldextra.com/momclick/activities/cheap-and-fun-gift-exchange-party-ideas/article_6623eab8-3b31-11e2-8263-001a4bcf887a.html\" target=_blank><img src=\"http://bloximages.chicago2.vip.townnews.com/heraldextra.com/content/tncms/assets/v3/editorial/b/bf/bbf30028-3b31-11e2-84c8-001a4bcf887a/50b9202b163b8.preview-620.jpg\" alt=\"MomClick\" width=\"275\" height=\"256\"></a>";
		  break;
		case 12:
		  retString = "<h1>Holiday <br />Appetizer Ideas:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Spoonful</b><br> <a href=\"http://spoonful.com/christmas/christmas-recipes/christmas-appetizers-snacks\" target=_blank><img src=\"http://static.spoonful.com/sites/default/files/styles/square_420x420/public/recipes/holiday-pretzel-treats-christmas-recipe-photo-420-FF0105ALMFA02.jpg?itok=UeMfGU8A\" alt=\"Spoonful\" width=\"275\" height=\"275\"></a> <br><br> <b>Allrecipes</b><br> <a href=\"http://allrecipes.com/recipes/holidays-and-events/christmas/appetizers/\" target=_blank><img src=\"http://images.media-allrecipes.com/userphotos/250x250/00/58/04/580469.jpg\" alt=\"Allrecipes\" width=\"275\" height=\"275\"></a> <br><br> <b>Martha Stewart</b><br> <a href=\"http://www.marthastewart.com/856473/20-years-living-best-christmas-appetizers/@center/1009060/christmas-appetizers\" target=_blank><img src=\"http://www.marthastewart.com/sites/files/marthastewart.com/imagecache/wmax-330/images/content/pub/ms_living/2007Q1/living_cheeseballs_p86_hd.jpg\" alt=\"Martha Stewart\" width=\"275\" height=\"334\"></a> <br><br> <b>Southern Living</b><br> <a href=\"http://www.southernliving.com/food/holidays-occasions/christmas-holiday-appetizer-recipes-00417000068898/\" target=_blank><img src=\"http://img4-1.southernliving.timeinc.net/i/2010/11/bacon-recipes/bacon-apple-bites-l.jpg?400:400\" alt=\"Southern Living\" width=\"275\" height=\"275\"></a> <br><br> <b>Food Network</b><br> <a href=\"http://www.foodnetwork.com/recipe-collections/christmas-appetizers/index.html\" target=_blank><img src=\"http://img.foodnetwork.com/FOOD/2003/11/10/mo1a06_prosciutto_figs_lead.jpg\" alt=\"Food Network\" width=\"275\" height=\"206\"></a> <br><br> <b>Country Living</b><br> <a href=\"http://www.countryliving.com/cooking/delectable-holiday-appetizers-1208#slide-1\" target=_blank><img src=\"http://www.countryliving.com/cm/countryliving/images/CL/CLX-prosciutto-fennel-w7gSG2-lgn.jpg\" alt=\"Country Living\" width=\"275\" height=\"367\"></a>";
		  break;
		case 13:
		  retString = "<h1>Handmade <br />Gift Boxes:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Petal Boxes</b><br> <a href=\"http://www.cutoutandkeep.net/projects/perfect-petal-boxes\" target=_blank><img src=\"http://images.coplusk.net/project_images/126563/image/full_070.jpg\" alt=\"Petal Boxes\" width=\"275\" height=\"231\"></a> <br><br> <b>Paper Boxes</b><br> <a href=\"http://www.cutoutandkeep.net/projects/paper-boxes\" target=_blank><img src=\"http://images.coplusk.net/project_images/144955/image/full_Paper_box1_002.jpg\" alt=\"Yahoo\" width=\"275\" height=\"206\"></a> <br><br> <b>Origami Gift Box</b><br> <a href=\"http://www.wikihow.com/Make-an-Origami-Gift-Box\" target=_blank><img src=\"http://pad1.whstatic.com/images/thumb/d/d3/Make-an-Origami-Gift-Box-Step-11-preview.jpg/-crop-163-119-163px-Make-an-Origami-Gift-Box-Step-11-preview.jpg\" alt=\"Origami Gift Box\" width=\"275\" height=\"201\"></a> <br><br> <b>Origami Boxes and Containers</b><br> <a href=\"http://www.origami-instructions.com/origami-boxes-and-containers.html\" target=_blank><img src=\"https://securecdn.disqus.com/uploads/mediaembed/images/579/2836/original.jpg\" alt=\"Origami Boxes and Containers\" width=\"275\" height=\"207\"></a>";
		  break;
		case 14:
		  retString = "<h1>Tree Skirts:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>11 Homemade Christmas Tree Skirt Ideas</b><br> <a href=\"http://www.allfreechristmascrafts.com/Christmas-Tree-Skirts/11-Homemade-Christmas-Tree-Skirt-Ideas\" target=_blank><img src=\"http://cf.primecp.com/master_images/AllFreeChristmasCrafts/Tree-Crafts/silent_night_op.jpg\" alt=\"11 Ideas\" width=\"275\" height=\"358\"></a> <br><br> <b>How to Make a No-Sew Ruffled Christmas Tree Skirt</b><br> <a href=\"http://www.hgtv.com/handmade/how-to-make-a-no-sew-ruffled-christmas-tree-skirt/index.html\" target=_blank><img src=\"http://img.hgtv.com/HGTV/2011/04/13/original_Marian-Parsons-Christmas-tree-skirt-beauty-with-presents_s4x3_lg.jpg\" alt=\"No-Sew Ruffled\" width=\"275\" height=\"207\"></a> <br><br> <b>10 Untraditional Tree Skirt Ideas</b><br> <a href=\"http://www.apartmenttherapy.com/10-nontraditional-tree-skirt-i-162320\" target=_blank><img src=\"http://p-ec1.pixstatic.com/51bb8417d9127e251e000056._w.540_s.fit_.jpg\" alt=\"Untraditional Ideas\" width=\"275\" height=\"387\"></a> <br><br> <b>5 Alternatives to Christmas Tree Skirts</b><br> <a href=\"http://www.apartmenttherapy.com/5-alternatives-to-christmas-tree-skirts-197075\" target=_blank><img src=\"http://p-ec2.pixstatic.com/5280f8f6697ab00e30003eb4._w.540_s.fit_.jpg\" alt=\"Alternatives\" width=\"275\" height=\"348\"></a>";
		  break;
		case 15:
		  retString = "<h1>Stockings:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Spoonful: 14 Christmas Stocking Crafts</b><br> <a href=\"http://spoonful.com/christmas/christmas-stocking-crafts\" target=_blank><img src=\"http://static.spoonful.com/sites/default/files/styles/square_420x420/public/crafts/elf-boot-christmas-stocking-craft-photo-420-FF1203STOCKA11.jpg?itok=Cch2wJG2\" alt=\"Spoonful\" width=\"275\" height=\"275\"></a> <br><br> <b>All Free Christmas Crafts: Stockings</b><br> <a href=\"http://www.allfreechristmascrafts.com/Christmas-Stockings-Crafts\" target=_blank><img src=\"http://cf2.primecp.com/master_images/AllFreeChristmasCrafts/Stocking-Crafts/fleece-stocking.jpg\" alt=\"All Free Christmas Crafts\" width=\"275\" height=\"412\"></a> <br><br> <b>Michaels: Stockings</b><br> <a href=\"http://www.michaels.com/Stockings/projects-christmas-stockings,default,sc.html\" target=_blank><img src=\"http://images.michaels.com/dw/staging/michaels-catalog/medium/e09802.jpg\" alt=\"Michaels\" width=\"275\" height=\"270\"></a> <br><br> <b>Country Living: Unique Christmas Stocking Craft</b><br> <a href=\"http://www.countryliving.com/crafts/projects/christmas-crafts/unique-christmas-stocking-craft-1210#slide-1\" target=_blank><img src=\"http://www.countryliving.com/cm/countryliving/images/FN/DIY-Holiday-Decor-stockings-1210-mdn.jpg\" alt=\"Country Living\" width=\"275\" height=\"367\"></a>";
		  break;
		case 16:
		  retString = "<h1>Greeting Cards:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Scrapbooks, Etc: Cards</b><br> <a href=\"http://www.scrapbooksetc.com/crafts/cards/\" target=_blank><img src=\"http://images.meredith.com/sbe/images/2009/11/l_alloccasioncards_10.jpg\" alt=\"Scrapbooks, Etc.\" width=\"275\" height=\"275\"></a> <br><br> <b>Martha Stewart: Butterfly Greeting Card</b><br> <a href=\"http://www.michaels.com/Martha-Stewart-Crafts-Butterfly-Greeting-Card/28120,default,pd.html\" target=_blank><img src=\"http://images2.layoutsparks.com/1/168884/whatever-happens-butterfly-purple.jpg\" alt=\"Martha Stewart\" width=\"275\" height=\"207\"></a> <br><br> <b>Pinterest: Greeting Card and Paper Crafts</b><br> <a href=\"http://www.pinterest.com/kellycox/greeting-card-and-paper-crafts/\" target=_blank><img src=\"http://media-cache-ak0.pinimg.com/736x/70/f9/32/70f9323d16416abcc86affb2285f9520.jpg\" alt=\"Pinterest\" width=\"275\" height=\"340\"></a> <br><br> <b>Better Homes And Gardens: 16 Creative Card-Making Ideas</b><br> <a href=\"http://www.bhg.com/crafts/easy/1-hour-projects/creative-card-making-ideas/\" target=_blank><img src=\"http://images.meredith.com/content/dam/bhg/Images/2007/04/100471123.jpg.rendition.largest.jpg\" alt=\"Better Homes And Gardens\" width=\"275\" height=\"306\"></a>";
		  break;
		case 17:
		  retString = "<h1>Green Decorating:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Pinterest: Greeting Card Card Craft Ideas - Reuse</b><br> <a href=\"http://www.pinterest.com/sdlium/greeting-card-card-craft-ideas-reuse/\" target=_blank><img src=\"http://media-cache-ak0.pinimg.com/736x/5b/e4/25/5be425259acc4b1f954984f8e07022aa.jpg\" alt=\"Pinterest\" width=\"275\" height=\"422\"></a> <br><br> <b>Good Housekeeping: Green Christmas Decorations</b><br> <a href=\"http://www.goodhousekeeping.com/holidays/christmas-ideas/green-christmas-decorations#slide-1\" target=_blank><img src=\"http://www.goodhousekeeping.com/cm/goodhousekeeping/images/Zf/christmas-wreath-1209-s3-medium_new.jpg\" alt=\"Good Housekeeping\" width=\"275\" height=\"367\"></a> <br><br> <b>Freshome: 10 Ways to Enjoy an Eco-friendly Christmas</b><br> <a href=\"http://freshome.com/2010/12/14/10-ways-to-enjoy-an-eco-friendly-christmas/\" target=_blank><img src=\"http://cdn.freshome.com/wp-content/uploads/2010/12/xmas-green_-natural-DIY.jpg\" alt=\"Freshome\" width=\"275\" height=\"206\"></a> <br><br> <b>TrendHunter: 23 Eco-friendly Ornaments</b><br> <a href=\"http://www.trendhunter.com/slideshow/ecofriendly-ornaments\" target=_blank><img src=\"http://3-ps.googleusercontent.com/x/www.trendhunter.com/cdn.trendhunterstatic.com/phpthumbnails/210/210745/600xNx210745_1_600.jpeg.pagespeed.ic.oi6BAs57_K.jpg\" alt=\"TrendHunter\" width=\"275\" height=\"275\"></a> <br><br> <b>Womans Day: 12 Homemade Holiday Decorations</b><br> <a href=\"http://www.womansday.com/home/holiday-decorating-ideas/12-homemade-holiday-decorations-112859#slide-1\" target=_blank><img src=\"http://www.womansday.com/cm/womansday/images/48/Natural-Selection-1-mdn.jpg\" alt=\"Womans Day\" width=\"275\" height=\"367\"></a> <br><br> <b>Inhabitat: How to Green Your Holiday</b><br> <a href=\"http://inhabitat.com/how-to-green-your-holidays-with-eco-friendly-christmas-decor/\" target=_blank><img src=\"http://assets.inhabitat.com/wp-content/blogs.dir/1/files/2012/10/cardboard-christmas-trees-537x387.jpg\" alt=\"Inhabitat\" width=\"275\" height=\"200\"></a>";
		  break;
		case 18:
		  retString = "<h1>Candle-Making:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Sugar-Bowl Candles</b><br> <a href=\"http://www.realsimple.com/holidays-entertaining/gifts/homemade-holiday-gifts-00000000024318/page13.html\" target=_blank><img src=\"http://img4-1.realsimple.timeinc.net/images/0912/homemade-bowl-candles_300.jpg\" alt=\"Sugar-Bowl Candles\" width=\"275\" height=\"344\"></a> <br><br> <b>Vellum 'Carol' Candles</b><br> <a href=\"http://diymaven.com/2010/12/19/vellum-carol-candles/\" target=_blank><img src=\"http://diymaven.files.wordpress.com/2010/12/img_0122.jpg?w=600\" alt=\"Vellum Carol Candles\" width=\"275\" height=\"206\"></a> <br><br> <b>Crockpot Candles</b><br> <a href=\"http://bonzaiaphrodite.com/2009/12/homemade-holidays-crock-pot-candles/\" target=_blank><img src=\"http://bonzaiaphrodite.com/wp-content/uploads/2009/12/IMG_1003.jpg\" alt=\"Crockpot Candles\" width=\"275\" height=\"183\"></a> <br><br> <b>Soy Candles</b><br> <a href=\"http://www.mybakingaddiction.com/homemade-holiday-gifts-soy-candles-and-glycerin-soap/\" target=_blank><img src=\"http://www.mybakingaddiction.com/wp-content/uploads/2012/12/IMG_9702-2.png\" alt=\"Soy Candles\" width=\"275\" height=\"382\"></a> <br><br> <b>More Ideas</b><br> <a href=\"http://motivanova.com/?p=3992\" target=_blank><img src=\"http://motivanova.com/wp-content/uploads/2013/11/Homemade-Christmas-Candles-Ideas_06.jpg\" alt=\"More Ideas\" width=\"275\" height=\"275\"></a>";
		  break;
		case 19:
		  retString = "<h1>Candle Holder <br />Crafts:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Recycled CD Christmas Candle Holder</b><br> <a href=\"http://dollarstorecrafts.com/2009/12/cd-candle-holder/\" target=_blank><img src=\"http://dollarstorecrafts.com/wp-content/uploads/2009/11/cd-candleholder.jpg\" alt=\"Recycled CDs\" width=\"266\" height=\"207\"></a> <br><br> <b>Mason Jar Christmas Candle Holders</b><br> <a href=\"http://putitinajar.com/2013/11/17/diy-mason-jar-christmas-candle-holders-using-glitter-craft-tutorial/\" target=_blank><img src=\"http://putitinajar.com/wp-content/uploads/2013/11/diy_mason_jar_glitter_vase_candle_holder.jpg\" alt=\"Mason Jars\" width=\"275\" height=\"184\"></a> <br><br> <b>Candy Cane Candle Holders</b><br> <a href=\"http://www.instructables.com/id/Christmas-Craft-Candy-Cane-Candlestick-Holders/\" target=_blank><img src=\"http://www.instructables.com/files/deriv/FCQ/932J/HABDGMXE/FCQ932JHABDGMXE.LARGE.jpg\" alt=\"Candy Canes\" width=\"275\" height=\"264\"></a> <br><br> <b>Etched Candle Holders</b><br> <a href=\"http://thediydreamer.com/christmas/etched-candle-holders-for-christmas/\" target=_blank><img src=\"http://thediydreamer.com/wp-content/uploads/2013/11/Christmas-Candle-Holders.jpg\" alt=\"Etched\" width=\"275\" height=\"229\"></a> <br><br> <b>Wax Paper Candle Holder</b><br> <a href=\"http://familycrafts.about.com/od/craftsticks/a/ElegantCandleHolder.htm\" target=_blank><img src=\"http://0.tqn.com/d/familycrafts/1/G/3/r/2/ElegantCandleHolder.jpg\" alt=\"Wax Paper\" width=\"275\" height=\"227\"></a> <br><br> <b>Simple Santa Candle Holder</b><br> <a href=\"http://www.mykidsguide.com/christmas-craft-for-kids-santa-candle-holder/\" target=_blank><img src=\"http://i1109.photobucket.com/albums/h430/OurFamilyWorld/My%20Kids%20Guide/Christmascraft2_zps645136cb.jpg\" alt=\"Simple Santa\" width=\"275\" height=\"367\"></a>";
		  break;
		case 20:
		  retString = "<h1>Handmade Gifts:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Marta Stewart: 54 Handmade Gift Ideas</b><br> <a href=\"http://www.marthastewart.com/275134/handmade-gifts-for-her/@center/307035/santas-workshop#949683\" target=_blank><img src=\"http://www.marthastewart.com/sites/files/marthastewart.com/imagecache/wmax-330/ecl/msliving-hires/2012/12_december/good_things/fabricboxes-104-mld109268_vert.jpg\" alt=\"Martha Stewart\" width=\"275\" height=\"379\"></a> <br><br> <b>Parents.com: Holiday Gifts Kids Can Make</b><br> <a href=\"http://www.parents.com/holiday/christmas/crafts/holiday-gifts-kids-can-make/\" target=_blank><img src=\"http://images.meredith.com/parents/images/2010/09/ss_101628837.jpg\" alt=\"Parents.com\" width=\"275\" height=\"275\"></a> <br><br> <b>Frugal Living: Free and Low-Cost Christmas Gifts That You Can Make</b><br> <a href=\"http://frugalliving.about.com/od/specialoccasions/tp/Free_Low_Cost_Christmas_Gifts.htm\" target=_blank><img src=\"http://0.tqn.com/d/frugalliving/1/G/4/-/-/-/chocolatespoon.jpg\" alt=\"Frugal Living\" width=\"275\" height=\"370\"></a> <br><br> <b>Thrifty Fun: Costume Jewelry Christmas Tree</b><br> <a href=\"http://www.thriftyfun.com/Making-a-Costume-Jewelry-Christmas-Tree.html\" target=_blank><img src=\"http://img.thrfun.com/img/083/231/vintage_tree_m1.jpg\" alt=\"Thrifty Fun\" width=\"275\" height=\"367\"></a> <br><br> <b>Beauty And Bedlam: Crafts Using Old Vintage Jewelry</b><br> <a href=\"http://beautyandbedlam.com/crafts-using-old-vintage-jewelry/\" target=_blank><img src=\"http://beautyandbedlam.com/wp-content/uploads/2012/04/wood-birds-with-vintage-jewelry.jpg\" alt=\"Beauty And Bedlam\" width=\"275\" height=\"207\"></a>";
		  break;
		case 21:
		  retString = "<h1>Wrapping Presents:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>BuzzFeed: 24 Cute And Incredibly Useful Gift Wrap DIYs</b><br> <a href=\"http://www.buzzfeed.com/alannaokun/24-cute-and-incredibly-useful-gift-wrap-diys\" target=_blank><img src=\"http://s3-ec.buzzfed.com/static/enhanced/webdr03/2012/11/15/13/enhanced-buzz-28238-1353002954-16.jpg\" alt=\"Buzzfeed\" width=\"275\" height=\"250\"></a> <br><br> <b>Laura Conrad: How To: Wrap a Perfect Present</b><br> <a href=\"http://laurenconrad.com/blog/post/how-to-wrap-a-perfect-present\" target=_blank><img src=\"http://dojys4nvh7tex.cloudfront.net/laurenconrad/dynamic/thumbnail/photo/yqaZMs1Tz3n7FhykpSX0YSTh.jpeg_600x0_R.png\" alt=\"Laura Conrad\" width=\"275\" height=\"183\"></a> <br><br> <b>Design Mom: Gift Wrapping 101</b><br> <a href=\"http://www.designmom.com/2012/12/4-secrets-to-wrapping-a-present/\" target=_blank><img src=\"http://www.designmom.com/wp-content/uploads/2012/12/how-to-wrap-a-present_8.jpg\" alt=\"Design Mom\" width=\"275\" height=\"387\"></a> <br><br> <b>WikiHow: How to Wrap a Present</b><br> <a href=\"http://www.wikihow.com/Wrap-a-Present\" target=_blank><img src=\"https://lh4.googleusercontent.com/-94yBs11QbUQ/TYKR2jJrQQI/AAAAAAAABn8/8jwgNhHWcoY/s1600/IMG_9573.JPG\" alt=\"WikiHow\" width=\"275\" height=\"183\"></a>";
		  break;
		case 22:
		  retString = "<h1>Bead Crafts:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Fave Crafts</b><br> <a href=\"http://www.favecrafts.com/Christmas-Crafts/9-Christmas-Crafts-to-Make-with-Beads/ct/1\" target=_blank><img src=\"http://www.favecrafts.com/master_images/Christmas-Crafts/beadedornament.jpg\" alt=\"Fave Crafts\" width=\"275\" height=\"174\"></a> <br><br> <b>Christmas Crafts</b><br> <a href=\"http://www.christmascrafts.com/bead-crafts.htm\" target=_blank><img src=\"http://www.christmascrafts.com/images/christmas-tree/ornate-bead-christmas-tree-ornament.JPG\" alt=\"Christmas Crafts\" width=\"275\" height=\"366\"></a> <br><br> <b>Love to Know Crafts</b><br> <a href=\"http://crafts.lovetoknow.com/wiki/Christmas_Crafts_Using_Beads\" target=_blank><img src=\"http://cf.ltkcdn.net/crafts/images/std/167044-141x349-beadsandblooms_beadtree_crop.jpg\" alt=\"Love to Know Crafts\" width=\"275\" height=\"681\"></a> <br><br> <b>Spoonful</b><br> <a href=\"http://spoonful.com/crafts/beaded-ornaments\" target=_blank><img src=\"http://static.spoonful.com/sites/default/files/styles/square_420x420/public/crafts/beaded-ornaments-christmas-craft-photo-420-FF1299GIFTA10.jpg?itok=GwwhZ9VY\" alt=\"Spoonful\" width=\"275\" height=\"275\"></a>";
		  break;
		case 23:
		  retString = "<h1>Christmas Jewelry:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Artbeads</b><br> <a href=\"http://www.artbeads.com/christmas-jewelry-craft-ideas.html\" target=_blank><img src=\"http://ep.yimg.com/ca/I/artbeads_2290_4923151980\" alt=\"Artbeads\" width=\"275\" height=\"206\"></a> <br><br> <b>The Ivey League</b><br> <a href=\"http://theiveyleague.com/2010/11/15/12-crafts-of-christmas-jewelry/\" target=_blank><img src=\"http://theiveyleague.com/wp-content/uploads/2010/11/jewelry-1-1024x682.jpg\" alt=\"The Ivey League\" width=\"275\" height=\"183\"></a> <br><br> <b>TLC</b><br> <a href=\"http://tlc.howstuffworks.com/family/how-to-make-christmas-jewelry.htm\" target=_blank><img src=\"http://static.ddmcdn.com/gif/how-to-make-christmas-jewelry-47.jpg\" alt=\"TLC\" width=\"275\" height=\"260\"></a> <br><br> <b>TrendHunter</b><br> <a href=\"http://www.trendhunter.com/slideshow/diy-christmas-jewelry-ideas\" target=_blank><img src=\"http://1-ps.googleusercontent.com/x/www.trendhunter.com/cdn.trendhunterstatic.com/thumbs/xtwo-shades-of-pink-chiffon.jpeg.pagespeed.ic.lZpnm62H5b.jpg\" alt=\"TrendHunter\" width=\"275\" height=\"257\"></a>";
		  break;
		case 24:
		  retString = "<h1>Cookies for <br />Santa & More <br />Christmas Eve Fun:</h1> <br><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>Santa Cookies</b><br> <a href=\"http://www.bettycrocker.com/recipes/jolly-santa-cookies/66f004f4-e7f3-4e50-9e29-9fbfff7e7585\" target=_blank><img src=\"http://s3.amazonaws.com/gmi-digital-library/8a9eeb2f-08ca-4bfb-a7d5-a077f464eb47.jpg\" alt=\"Santa Cookies\" width=\"275\" height=\"207\"></a> <br><br> <b>Reindeer Food</b><br> <a href=\"http://kidscooking.about.com/od/christmasrecipes/r/reindeerfood.htm\" target=_blank><img src=\"http://0.tqn.com/d/kidscooking/1/I/d/T/-/-/reindeer-food.jpg\" alt=\"Reindeer Food\" width=\"275\" height=\"216\"></a> <br><br> <b>Decorated Cookies</b><br> <a href=\"http://www.delish.com/entertaining-ideas/holidays/christmas/decorated-christmas-cookies#slide-1\" target=_blank><img src=\"http://www.delish.com/cm/delish/images/OT/candy-cane-cookies-lg.jpg\" alt=\"Decorated Cookies\" width=\"275\" height=\"275\"></a> <br><br> <b>Christmas Cake Pop Pals</b><br> <a href=\"http://www.wilton.com/idea/Christmas-Cake-Pop-Pals\" target=_blank><img src=\"http://d3w5aos35qel1w.cloudfront.net/img/cake-pop-pal-main.jpg\" alt=\"Christmas Cake Pop Pals\" width=\"275\" height=\"275\"></a> <br><br> <b>Christmas Desserts</b><br> <a href=\"http://spoonful.com/christmas/best-christmas-desserts-gallery\" target=_blank><img src=http://static.spoonful.com/sites/default/files/styles/square_420x420/public/recipes/towering-tree-cake-christmas-recipe-photo-420-FF0106TREEA17.jpg?itok=IVy3gbBw\" alt=\"Christmas Desserts\" width=\"275\" height=\"275\"></a>";
		  break;
		case 25:
		  retString = "<h1>Christmas Day <br />Fun:</h1><br> <h3><i>Merry Christmas!</i></h3><br> <i>To go back, click the 3 dots in the bottom<br /> right corner and then press back.</i><br><br> <b>100 Christmas Activities & Crafts</b><br> <a href=\"http://www.growingajeweledrose.com/2012/10/100-christmas-activities-and-crafts-for.html\" target=_blank><img src=\"http://3.bp.blogspot.com/_2uFF9x0UJZs/TOqxtM8W3_I/AAAAAAAAG90/U2-05tS7D-g/s640/3handprints.jpg\" alt=\"100 Christmas Activities & Crafts\" width=\"275\" height=\"186\"></a> <br><br> <b>Create Christmas Traditions</b><br> <a href=\"http://www.kidspot.com.au/Christmas/Christmas-traditions-Create-family-traditions-Create-personal-family-Christmas-traditions+3728+659+article.htm\" target=_blank><img src=\"http://d33y93cfm0wb4z.cloudfront.net/Christmas/2Girldecoratinggingerbreadhouse476x290.jpg\" alt=\"Create Christmas Traditions\" width=\"275\" height=\"168\"></a> <br><br> <b>Fun Christmas Games</b><br> <a href=\"http://www.moneycrashers.com/fun-christmas-games-activities-kids-adults-parties/\" target=_blank><img src=\"http://cdn.moneycrashers.com/wp-content/uploads/2010/12/Christmas-Activity1-e1292553508134.jpg\" alt=\"Fun Christmas Games\" width=\"275\" height=\"243\"></a> <br><br> <b>10 Tips for Christmas Eve or Christmas Day Activities</b><br> <a href=\"http://momitforward.com/family-activities-fun-ways-to-celebrate-christmas-eve-and-christmas-day\" target=_blank><img src=\"http://momitforward.com/wp-content/uploads/2011/12/Christmas-Ornaments.jpg\" alt=\"10 Tips for Christmas Eve or Christmas Day Activities\" width=\"275\" height=\"183\"></a> <br><br> <b>Things to Do on Christmas</b><br> <a href=\"http://thehilljean.com/2012/12/things-to-do-on-christmas.html\" target=_blank><img src=\"http://thehilljean.com/wp-content/uploads/2012/12/candace-and-i.jpg\" alt=\"Things to Do on Christmas\" width=\"275\" height=\"183\"></a>";
		  break;
	} 
    return retString;
}
